# 树莓派人脸识别监控系统默认配置文件

# 摄像头配置
camera:
  # 摄像头类型: picamera2, opencv, libcamera
  type: "picamera2"
  # 摄像头设备ID (对于OpenCV)
  device_id: 0
  # 分辨率
  resolution:
    width: 640
    height: 480
  # 帧率
  fps: 30
  # 其他摄像头特定参数
  options:
    brightness: 50
    contrast: 50
    saturation: 50

# 人脸识别配置
face_recognition:
  # 模型配置
  model: "cnn"  # 或 "hog" 更快但精度较低
  # 人脸数据库路径
  known_faces_dir: "./data/known_faces"
  # 检测阈值（越小越严格）
  tolerance: 0.5
  # 是否保存检测到的未知人脸
  save_unknown_faces: false
  unknown_faces_dir: "./data/unknown_faces"
  # 每秒检测帧数（可低于摄像头帧率以减少CPU占用）
  detection_fps: 5

# 监控配置
monitoring:
  # 是否在程序启动时自动启动监控
  auto_start: true
  # 是否启用运动检测前置过滤
  enable_motion_detection: true
  # 运动检测灵敏度 (1-100)
  motion_sensitivity: 70
  # 运动检测帧率（可低于摄像头帧率以降低CPU占用）
  motion_detection_fps: 10
  # 是否记录所有检测事件
  log_all_detections: false
  # 日志文件路径
  log_file: "./logs/detections.log"
  # 检测到人脸后的动作
  actions:
    # 是否保存图片
    save_image: false
    # 图片保存位置
    images_dir: "./data/detected_images"
    # 是否发送通知
    send_notification: false
  # 用于显示中文的字体文件路径
  font_path: "assets/fonts/wqy-zenhei.ttc"
  # 显示名称的字体大小
  font_size: 15

# Web界面配置
web_interface:
  # 是否启用Web界面
  enabled: true
  # Web服务监听地址
  host: "0.0.0.0"
  # Web服务端口
  port: 8080
  # Web视频流帧率
  streaming_fps: 30
  # 是否启用认证
  auth_required: true
  # 用户凭据
  credentials:
    username: "admin"
    password: "admin123"

# 显示配置
display:
  # 人脸框在屏幕上的绘制冷却时间（秒）
  draw_cooldown: 5
  # 人脸框在识别后保留在屏幕上的时间（秒）
  box_retention: 3

# 检测配置
detection:
  detection_fps: 5  # 检测帧率
  min_face_size: 20  # 最小人脸尺寸
  scale_factor: 1.1  # 图像金字塔缩放因子
  min_neighbors: 5  # 最小邻居数
  detection_interval: 0.2  # 检测间隔（秒）

# 日志配置
logging:
  level: INFO
  file: logs/facerec.log
  max_size: 10485760  # 10MB
  backup_count: 5 